services:
  jurassip:
    image: jurassip:v0.1.0
    container_name: jurassip
    build:
      dockerfile: ../Jurassip/Dockerfile
      context: ../Jurassip
    environment:
      - SERIAL_PORT_NAME=/dev/ttyAMA2
      - SERIAL_BAUD_RATE=9600
      - GRPC_SERVER_HOST=0.0.0.0
      - GRPC_SERVER_PORT=50051
    networks:
      - blockcaffeine
    volumes:
      - /dev/ttyAMA2:/dev/ttyAMA2:ro
    privileged: true
    restart: unless-stopped

  anteiku:
    image: anteiku:v0.1.0
    container_name: anteiku
    build:
      dockerfile: ../Anteiku/Dockerfile
      context: ../Anteiku
    environment:
      - GRPC_SERVER_HOST=jurassip
      - GRPC_SERVER_PORT=50051
      - BLOCKCHAIN_RPC_URL=https://fortuna.informatik.uni-mannheim.de:32779
      - CONTRACT_ADDRESS=0xC495f6FF1912FB7cC33C65c3f8542aE78044D3C0
    networks:
      - blockcaffeine
    restart: unless-stopped

  espressos:
    image: espressos:v0.2.0
    container_name: espressos
    build:
      dockerfile: ../EspressOS/Dockerfile
      context: ../EspressOS      
    environment:
      - PUBLIC_CAFEREUM_ADDRESS=0xC495f6FF1912FB7cC33C65c3f8542aE78044D3C0
    networks:
      - blockcaffeine
    restart: unless-stopped

  caddy:
    build:
      dockerfile: ./caddy/Dockerfile
    container_name: caddy
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./caddy/data:/data
      - ./caddy/config:/config
    environment:
      - CLOUDFLARE_API_TOKEN=${CLOUDFLARE_API_TOKEN}
    networks:
      - blockcaffeine
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped

networks:
  blockcaffeine:
    name: blockcaffeine
    driver: bridge
