services:
  jurassip:
    image: jurassip:v0.1.0
    container_name: jurassip
    build:
      dockerfile: ../Jurassip/Dockerfile
      context: ../Jurassip
    environment:
      - SERIAL_PORT_NAME=/dev/ttyAMA2
      - SERIAL_BAUD_RATE=9600
      - GRPC_SERVER_HOST=0.0.0.0
      - GRPC_SERVER_PORT=50051
    networks:
      - blockcaffeine
    volumes:
      - /dev/ttyAMA2:/dev/ttyAMA2:ro
    privileged: true
    restart: unless-stopped

  anteiku:
    image: anteiku:v0.1.0
    container_name: anteiku
    build:
      dockerfile: ../Anteiku/Dockerfile
      context: ../Anteiku
    environment:
      - GRPC_SERVER_HOST=jurassip
      - GRPC_SERVER_PORT=50051
      - BLOCKCHAIN_RPC_URL=https://fortuna.informatik.uni-mannheim.de:32779
      - CONTRACT_ADDRESS=0xfA87eB3A4a16D9df4FFdC9167EC4E24BA3382c57
    networks:
      - blockcaffeine
    restart: unless-stopped

  espressos:
    image: espressos:v0.1.0
    container_name: espressos
    build:
      dockerfile: ../EspressOS/Dockerfile
      context: ../EspressOS      
    networks:
      - blockcaffeine
    restart: unless-stopped

  caddy:
    image: caddy:2:10.0
    container_name: caddy
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/data:/data
      - ./caddy/config:/config
    networks:
      - blockcaffeine
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped

networks:
  blockcaffeine:
    name: blockcaffeine
    driver: bridge
